version: "2"
services:
  node:
    image: "node:alpine3.11"
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    command: "npm start"
